services:
  docker_dashboard:
    build: .
    image: ghcr.io/rvdxse/dockerlobby:${LOBBY_IMAGE_TAG:-latest}
    container_name: dashboard_container
    ports:
      - "80:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
