name: Deploy

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.head_branch == 'main')
    runs-on: ubuntu-24.04-arm
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml
      - name: Join ZeroTier Network
        uses: zerotier/github-action@v1.0.3
        with:
          network_id: ${{ secrets.ZEROTIER_NETWORK_ID }}
          auth_token: ${{ secrets.ZEROTIER_CENTRAL_TOKEN }}

      - name: Wait for ZT connection
        run: |
          for i in $(seq 1 30); do
            ping -c 1 -W 2 ${{ secrets.RPI_ZT_IP }} > /dev/null 2>&1 && echo "Reachable!" && break
            echo "Attempt $i failed, retrying..."
            sleep 5
          done
      - name: Generate inventory
        run: |
            sed "s/{{ RPI_HOST }}/${{ secrets.RPI_ZT_IP }}/g; \
                s/{{ RPI_USER }}/${{ secrets.RPI_USER }}/g" \
            ansible/inventory/hosts.ini.template > ansible/inventory/hosts.ini
      - name: Deploy
        id: ansible_deploy
        uses: dawidd6/action-ansible-playbook@v7
        with:
          playbook: ansible/playbooks/deploy.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            -i ansible/inventory/hosts.ini
            -e registry_token=${{ secrets.REGISTRY_TOKEN }}
            -e registry_user=${{ github.repository_owner }}
